library(geoR)
loci<-as.geodata(Polylepis_Loci_Polimorfico,coords.col=3:4, data.col=2)
loci.v<-variog(loci, max.dist=10)
points(loci)
plot(loci.v)
loci.vfgauss<-variofit(loci.v, cov.model="gauss")
lines(loci.vfgauss)
#loci.vfexp<-variofit(loci.v, cov.model="exp")
#lines(loci.vfexp)
#loci.vfsphe<-variofit(loci.v, cov.model="sphe")
#lines(loci.vfsphe)
#loci.vflinear<-variofit(loci.v, cov.model="linear")
#lines(loci.vflinear)
gr<-expand.grid(x=seq(-66, -64, by=0.05) , y=seq(-32, -22, by=0.05))
KC.g<-krige.control(obj.model=loci.vfgauss)
loci.vfg.K<-krige.conv(loci, loc=gr, krige=KC.g)
image(loci.vfg.K, loc=gr, col=gray(seq(1,0, l=11)))
points(loci, add=T, cex.max=2)