library(geoR)
acoorp<-as.geodata(Polylepis,coords.col=253:254, data.col=258)
acoorp.v<-variog(acoorp, max.dist=800)
plot(acoorp.v)
acoorp.vfgauss<-variofit(acoorp.v, cov.model="gauss")
lines(acoorp.vfgauss)
#acoorp.vfexp<-variofit(acoorp.v, cov.model="exp")
#lines(acoorp.vfexp)
#acoorp.vfsphe<-variofit(acoorp.v, cov.model="sphe")
#lines(acoorp.vfsphe)
#acoorp.vflinear<-variofit(acoorp.v, cov.model="linear")
#lines(acoorp.vflinear)
gr<-expand.grid(x=seq(-66, -64, by=0.05) , y=seq(-32, -22, by=0.05))
KC.g<-krige.control(obj.model=acoorp.vfgauss)
acop.vfg.K<-krige.conv(acoorp, loc=gr, krige=KC.g)
image(acop.vfg.K, loc=gr, col=gray(seq(1,0, l=11)))
points(acoorp, add=T, cex.max=2)