library(geoR)
Prosopis.g<-as.geodata(CP1e_xy_Prosopis,coords.col=3:4, data.col=1)
Prosopis.v<-variog(Prosopis.g, max.dist=300)
plot(Prosopis.v)
Prosopis.vfgauss<-variofit(Prosopis.v, cov.model="gauss")
#Prosopis.vfexp<-variofit(Prosopis.v, cov.model="exp")
#Prosopis.vfsphe<-variofit(Prosopis.v, cov.model="sphe")
lines(Prosopis.vfgauss)
#lines(Prosopis.vfexp)
#lines(Prosopis.vfsphe)
gr<-expand.grid(x=seq(144, 854, by=2) , y=seq(202, 772, by=2))
KrigCont<-krige.control(obj.mo=Prosopis.vfgauss)
Prosopis.vfgauss.K<-krige.conv(Prosopis.g, loc=gr, krige=KrigCont)
image(Prosopis.vfgauss.K, loc=gr , col=grey(seq(0,1,1/21)))
points(Prosopis.g, add=T, cex.max=2)