library(geoR)
ACPgeo<-as.geodata(Polylepis_Frecuencias.alelicas,coords.col=494:495, data.col=496)
is.geodata(ACPgeo)
ACPgeo.v<-variog(ACPgeo, max.dist=800)
points(ACPgeo)
plot(ACPgeo.v)
acp.vfgauss<-variofit(ACPgeo.v, cov.model="gauss")
#acp.vfexp<-variofit(ACPgeo.v, cov.model="exp")
#acp.vfsphe<-variofit(ACPgeo.v, cov.model="sphe")
#acp.vfl<-variofit(ACPgeo.v, cov.model="linear")
lines(acp.vfgauss)
#lines(acp.vfexp)
#lines(acp.vfsphe)
#lines(spca.vfl)
gr<-expand.grid(x=seq(-66, -64, by=0.05) , y=seq(-32, -22, by=0.05))
KrigCont<-krige.control(obj.mo=acp.vfgauss)
acp.vfgauss.K<-krige.conv(ACPgeo, loc=gr, krige=KrigCont)
image(acp.vfgauss.K, loc=gr , col=grey(seq(0,1,1/21)))
points(ACPgeo, add=T, cex.max=2)